# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby_apk 0.7.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby_apk"
  s.version = "0.7.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["SecureBrain"]
  s.date = "2020-07-13"
  s.description = "static analysis tool for android apk"
  s.email = "info@securebrain.co.jp"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "ruby_apk.gemspec",
    *Dir["lib/**/*"],
    *Dir["spec/**/*"],
  ]
  s.homepage = "https://github.com/SecureBrain/ruby_apk/"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "static analysis tool for android apk"

  s.specification_version = 4
  s.add_runtime_dependency(%q<rubyzip>, [">= 1.3.0", "~> 1.3"])
  s.add_development_dependency(%q<rspec>, [">= 2.11.0", "~> 2.11"])
  s.add_development_dependency(%q<bundler>, [">= 2.1.4", "~> 2.1"])
  s.add_development_dependency(%q<jeweler>, [">= 2.3.9", "~> 2.3"])
  s.add_development_dependency(%q<yard>, ["~> 0"])
  s.add_development_dependency(%q<redcarpet>, ["~> 3.2"])
  s.add_development_dependency(%q<simplecov>, ["~> 0"])
  s.add_development_dependency(%q<pry>, ["~> 0"])
end

